### ISSUE TITLE
Command registers even with extra parameters in input

### ISSUE THREAD

**Issue by weidak** [weidak/pe#1]
The deletion command works even when there is additional parameters in between the command and the prefixes.

`delete_class test c/hello`

![image.png](https://raw.githubusercontent.com/weidak/pe/main/files/2c8194a2-0d63-4fbd-a76e-396984355151.png)

**Comment by nus-pe-script** [comment]
# Team's Response
Ui related.

Does not cause any unintentional deletion due to the `CLASS_ID` being explicitly stated with `c/` and duplicated parameters will cause an error message. (Note: `CLASS_ID` cannot contain `/`).

In other cases, it is intended to allow flexibility for users when arrow keys do not work in some Terminals (eg. Bash).

For example:
* User intends to edit a student's name to a long text and forgets to enter `c/` to indicate the class.
  * Initial (missing `c/`): `edit_student CS2113T-F11 s/1 i/a03452345x n/This is a name that is super long to the point it is troublesome to reenter`
  * Quick Fix (append `c/CS2113T-F11`): `edit_student CS2113T-F11 s/1 i/a03452345x n/This is a name that is super long to the point it is troublesome to reenter c/CS2113T-F11`


# Items for the Tester to Verify
## :question: Issue response

Team chose [`response.Rejected`]





- [x] I disagree

**Reason for disagreement:** I agree with the flexibility use case as demonstrated above. However, I believe this is still on the onus of the user to key in the prefix of c/ properly as it was stated clearly in the user guide. If this was intentional, maybe it could have been brought it up under the "Quick Notes" section of the User Guide informing users that extra parameters will be ignored. :) I'm bringing it up because I'm sure I won't be the only one indicating the acceptance of additional parameters, and it is on the team to handle extra input.

-------------------
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.Low`]

- [x] I disagree

**Reason for disagreement:** As this is related to user-input and error handling, not just cosmetics, I believe it should at least retain a severity of low instead.

-------------------
