### ISSUE TITLE
Empty inputs are not handled for parser

### ISSUE THREAD

**Issue by weidak** [weidak/pe#4]
When a user inputs an empty input, it does not state whether the command is invalid or prompts the user to type "help" if he was lost. 

The below screenshot shows multiple empty inputs:

![image.png](https://raw.githubusercontent.com/weidak/pe/main/files/6ad1fb78-4d01-4490-b3c3-42756ba16a49.png)

**Comment by nus-se-script** [comment]
# Team's Response
Cosmetic/Ui related.

This is not a bug.

This is intended as the `Taa` class calls `ui.getUserInput()` and it only returns when the input is a non empty string. This is to allow users to clear the command space similar to in command prompt.


# Items for the Tester to Verify
## :question: Issue response

Team chose [`response.Rejected`]







- [x] I disagree

**Reason for disagreement:** I was slightly confused when I was able to perform this action, and I believe the team should have some documentation on it. Though it is minor, I believe we should be prompted by the application to enter a command instead, maybe with "help" prompting the users.

-------------------
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.Low`]

- [x] I disagree

**Reason for disagreement:** Since this is something to do with their error handling, I believe this should retain the level of "low" as this was not handled in a more intuitive manner.

-------------------
