### ISSUE TITLE
No command was called to construct the :ClassList

### ISSUE THREAD

**Issue by weidak** [weidak/pe#8]
In the same architecture sequence diagram on page 3, the command that calls the constructor of :ClassList is missing.

Should at least have new ClassList()

![image.png](https://raw.githubusercontent.com/weidak/pe/main/files/eb0f1d29-5673-4548-ae3a-17e7e47c1e82.png)

**Comment by nus-pe-script** [comment]
# Team's Response
Format related. Does not hinder understanding that it is an object creation as it explicitly points to the classname instead of an activation bar.

The textbook only states the object creation notations are:
* The arrow that represents the constructor arrives at the side of the box representing the instance.
* The activation bar represents the period the constructor is active.

Reference: https://nus-cs2113-ay2122s1.github.io/website/se-book-adapted/chapters/uml.html#object-creation


# Items for the Tester to Verify
## :question: Issue response

Team chose [`response.Rejected`]





- [x] I disagree

**Reason for disagreement:** Thank you for including the reference link. As seen in the reference link:


![image.png](https://raw.githubusercontent.com/weidak/pe/main/files/d682101c-d4f4-4c9d-9803-14ca7ebe1389.png)

There are method calls to construct these objects. Speaking from a personal anecdote during tutorial lessons, my tutor also brought up that constructor methods were missing from my sequence diagram. Aligning with these teachings, I believe this should be considered a bug as they did not mention that the method call was supposed to be optional.

-------------------
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.Medium`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------
